routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');

// administrators section of routes
Route::group(['middleware' => ['auth_flash_message'], 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('roles-permissions-management', 'RolesPermissionsManagementController@index')->name('admin.roles-permissions-management');
    Route::resource('settings', 'SettingController');
    Route::resource('users', 'UserController');
    Route::post('settings/bulk-update', 'SettingController@bulkUpdate')->name('admin.settings.bulk_update');
});

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('socilite_login');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('socilite_callback');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Hash;
use EloquentFilter\Filterable;
use App\ModelFilters\UserFilter;
use Kyslik\ColumnSortable\Sortable;
use App\Traits\ModelUtilities;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Addressable;

class User extends Authenticatable
{

    use Notifiable, HasRoles, Filterable, Sortable, ModelUtilities, Searchable, SoftDeletes, Addressable;

    protected $with = ['roles'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'provider_data' => 'array',
        'is_active' => 'boolean',
    ];

    public function modelFilter()
    {
        return $this->provideFilter(UserFilter::class);
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * setPasswordAttribute mutator automatically hash password via eloquent model.
     *
     * @param $password
     *
     * @return void
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    /**
     * Get the index name for the model for laravel scout
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'users_index';
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        return $this->toArray();
    }

    public function getHasAvatarUrlAttribute()
    {
        if (trim($this->avatar_url) != "") {
            return true;
        }
        return false;
    }


}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Repositories\UsersRepository;
use App\Models\User;
use App\Http\Controllers\Controller;
use Illuminate\Pagination\Paginator;
use App\Traits\APIPagination;

class UserController extends Controller
{
    use APIPagination;

    private $usersRepository;

    /**
     * UserController constructor.
     *
     * @param $usersRepository
     */
    public function __construct(UsersRepository $usersRepository)
    {
        $this->usersRepository = $usersRepository;
    }

    public function dataSource(Request $request)
    {
        extract($this->preparePagination($request), EXTR_SKIP);
        return User::filter($request->all())->paginate($limit)->toJson();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Repositories\UsersRepository;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Http\Requests\StoreUser;

class UserController extends Controller
{

    private $usersRepository;

    private $itemsPerPage;

    /**
     * UserController constructor.
     *
     * @param $usersRepository
     */
    public function __construct(UsersRepository $usersRepository)
    {
        $this->usersRepository = $usersRepository;
        $this->itemsPerPage = 10;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $itemsPerPage = $request->get('itemsPerPage', $this->itemsPerPage);
        return $this->autoRender([
            'users' => User::filter($request->all())->sortable()->paginate($itemsPerPage),
            'itemsPerPage' => $itemsPerPage
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->autoRender();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends("layouts.robust.admin")

@section("content_header")
    @include("layouts.robust.partials.content_header", ["title" => "Create User"])
@stop

@section("content")
    <div class="row">
        <div class="col-xs-12">
            @component('admin.partials.card', ['cardTitle' => 'Create User', 'cardText' => 'Enter the details below to create a new user'])
                <create-edit-user
                        cancel-url="{{route('users.index')}}"
                        save-url="{{route('users.store')}}"></create-edit-user>
            @endcomponent
        </div>
    </div>
@stop

resources/views/admin/user/index.blade.php
@extends("layouts.robust.admin")

@section("content_header")
    @include("layouts.robust.partials.content_header", ["title" => "Users"])
@stop

@section("content")
    <div class="row">
        <div class="col-xs-12">
            @component('admin.partials.card', ['cardTitle' => 'Manage Users'])
                <div class="row">
                    <div class="col-xs-12 col-md-2">
                        @include("admin.partials.items_per_page", ["itemsPerPage" => $itemsPerPage, "target" => "user"])
                    </div>
                    <div class="col-xs-12 col-md-5">
                        {{Form::open(['route' => 'users.index','method' => 'GET', 'class' => 'form', 'style' => "margin-top: 1rem; margin-bottom: 1rem;"])}}
                        <div class="row">
                            <div class="col-md-10">
                                <div class="input-group">
                                    {{Form::text('query',
                                                trim(Request::query('query')),
                                                ['name' => 'query', 'class' => 'form-control', 'placeholder' => 'Search...'])}}
                                    {{Form::hidden('itemsPerPage', $itemsPerPage)}}
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="submit">
                                            <i class="icon-search7"></i>
                                        </button>
                                        <a class="btn btn-secondary"
                                           data-toggle="tooltip"
                                           data-placement="top"
                                           title="Reset Search"
                                           data-original-title="Reset Search"
                                           href="{{route('users.index')}}">
                                            <i class="icon-repeat2"></i>
                                        </a>
                                    </span>
                                </div>
                            </div>
                        </div>
                        {{Form::close()}}
                    </div>
                    <div class="col-xs-12 col-md-5">
                        <div class="pull-right">{{$users->appends(\Request::except('page'))->render()}}</div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-condensed table-striped">
                        <thead>
                        <tr>
                            <th><i class="icon-head"></i> @sortablelink('name', 'Name')</th>
                            <th><i class="icon-mail6"></i> @sortablelink('email', 'Email')</th>
                            <th><i class="icon-users"></i> Roles</th>
                            <th><i class="icon-check2"></i> @sortablelink('active', 'Active')</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    @foreach($user->roles as $role)
                                        <span class="tag tag-default"
                                              data-toggle="tooltip"
                                              data-placement="top"
                                              title="{{$role->description}}"
                                              data-original-title="{{$role->name}}">{{$role->name}}</span>
                                    @endforeach
                                </td>
                                <td>@include("partials.is_active_icon", ["active" => $user->is_active])</td>
                                <td></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="pull-right">{{$users->appends(\Request::except('page'))->render()}}</div>
            @endcomponent
        </div>
    </div>
@stop